CREATE SEQUENCE SEQ_CTC_LOCALIZACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CTC_LOCALIZACAO (
    LOCALIZACAO_ID INTEGER DEFAULT SEQ_CTC_LOCALIZACAO.NEXTVAL NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(10)
);