CREATE SEQUENCE SEQ_CTC_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CTC_USUARIO (
    USUARIO_ID INTEGER DEFAULT SEQ_CTC_USUARIO.NEXTVAL NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    ROLE VARCHAR(50) DEFAULT 'USER' NOT NULL,
    LOCALIZACAO_ID INTEGER,
    CONSTRAINT email_unico_citycare UNIQUE (EMAIL)
);