CREATE SEQUENCE SEQ_CTC_OCORRENCIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_CTC_OCORRENCIA(
    OCORRENCIA_ID INTEGER DEFAULT SEQ_CTC_OCORRENCIA.NEXTVAL NOT NULL,
    OCORRENCIA VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(240) NOT NULL,
    DT_OCORRENCIA DATE DEFAULT CURRENT_DATE,
    STATUS VARCHAR(30) DEFAULT 'PENDENTE' NOT NULL,
    LOCALIZACAO_ID INTEGER,
    DT_RESOLUCAO DATE
)